### ISSUE TITLE
Handle default character encoding

### ISSUE THREAD

**Issue by ourcontact** [Plutoberth/python-launch-library#1]
Would it be reasonable for this library to unidecode names?

For example: From https://launchlibrary.net/
convert Soyuz 2.1a/Fregat | Kanopus-V №5 & Kanopus-V №6
to Soyuz 2.1a/Fregat | Kanopus-V No. 5 & Kanopus-V No. 6
in order to avoid errors such as
UnicodeEncodeError: 'ascii' codec can't encode character '\u2116' in position 30: ordinal not in range(128)
without using unidecode(launches[x].name) in every reference

**Comment by Plutoberth** [comment]
@ourcontact Oh hi! For some bizarre reason, Github never notified me about this issue, and I randomly found it here today. I'll fix this soon.

**Comment by Plutoberth** [comment]
Hey there,

I've reproduced the bug using 

`launch_object.name.encode().decode("ascii")`

I added the optional `unicode` parameter to the API class. You can set it to false to enable the use of unidecode.

Here's an example:

```py
>>> import launchlibrary as ll
>>> unicode = ll.Api(unicode=True)
>>> ascii = ll.Api(unicode=False)
>>> ll.Launch.fetch(unicode, name="Kanopus")[0].name
'Soyuz-FG/Fregat | Kanopus-V №1 & BelKA-2'
>>> ll.Launch.fetch(ascii, name="Kanopus")[0].name
'Soyuz-FG/Fregat | Kanopus-V No. 1 & BelKA-2'
```

I uploaded the change to Pypi so you should be able to upgrade by using `python -m pip install python-launch-library --upgrade`
