### ISSUE TITLE
'Api' object has no attribute 'send_message'

### ISSUE THREAD

**Issue by genev** [Plutoberth/python-launch-library#11]
Python 3.8.5 (default, Jul 21 2020, 10:42:08)
>>> import launchlibrary as ll
>>> print(ll.Launch.fetch(ll.Api())

I get the following:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/launchlibrary/models.py", line 73, in fetch
    json_object = network.send_message(cls._endpoint_name, kwargs)
AttributeError: 'Api' object has no attribute 'send_message'`

**Comment by Plutoberth** [comment]
Hi,

I introduced a breaking change some time ago (with a major version bump) that made the library much easier to use. I forgot to update the README to reflect the changes, so I did that now. Note the changelog:

Snippet:



* 1.0 - Changed all fetch calls to be through the Api object. This is a breaking change.
  

  
  ```python
  # Porting guide

  import launchlibrary as ll
  api = ll.Api()
  
  # Before
  next_launch = ll.Launch.next(api, 1)
  
  # After
  next_launch = api.next_launches(1)
  ```

**Comment by genev** [comment]
Thanks, @Plutoberth!
