### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by willschlitzer** [Plutoberth/python-launch-library#5]
Currently getting a ModuleNotFoundError when running "import launchlibrary"
Listed below are the contents of my requirements file, populated entirely (minus the Python version) from "pip install python-launch-library"

Python 3.7.0
aiohttp==3.6.2
async-timeout==3.0.1
attrs==19.3.0
certifi==2020.6.20
chardet==3.0.4
idna==2.10
multidict==4.7.6
python-dateutil==2.8.1
python-launch-library==1
requests==2.24.0
six==1.15.0
Unidecode==1.1.1
urllib3==1.25.9
yarl==1.4.2

**Comment by Plutoberth** [comment]
Hey,

This doesn't look like it's related to `python-launch-library`. I just downloaded the library on a new computer and it works on my machine™️. Could it be that your python and pip installations are not pointing to the same installation (i.e. pip is for python3.7, python is for python 3.6)? What happens if you install using `python -m pip install python-launch-library`?

By the way, including all of your sub-deps in your requirements.txt file might cause problems. The deps for `python-launch-library` (or any other lib you're using) will probably change, at least slightly, in the future.

**Comment by Plutoberth** [comment]
Since you didn't respond, I'm closing this issue.

**Comment by willschlitzer** [comment]
Hi Plutoberth, sorry that I never got around to responding to this the first time *facepalm*

I'm still having trouble with this. I'm using a difference machine and have set up a clean environment with Python3 .8. Here are the results from my `pip freeze` comment:

aiohttp==3.7.2
async-lru==1.0.2
async-timeout==3.0.1
attrs==20.2.0
certifi==2020.6.20
chardet==3.0.4
idna==2.10
multidict==5.0.0
python-dateutil==2.8.1
python-launch-library==1.0.6
requests==2.24.0
six==1.15.0
typing-extensions==3.7.4.3
Unidecode==1.1.1
urllib3==1.25.11
yarl==1.6.2


I initially had issues where it wouldn't build the wheel when I installed it, but that seemed fixed when I did `pip install wheel`. I'm not sure how to properly install this module, as I'm still getting a ModuleNotFoundError when I try `import launchlibrary` in both the Python console and in a script.

UPDATE: I don't know what I did wrong, but it's working!

**Comment by Plutoberth** [comment]
> 
> 
> Hi Plutoberth, sorry that I never got around to responding to this the first time _facepalm_
> 
> I'm still having trouble with this. I'm using a difference machine and have set up a clean environment with Python3 .8. Here are the results from my `pip freeze` comment:
> 
> aiohttp==3.7.2
> async-lru==1.0.2
> async-timeout==3.0.1
> attrs==20.2.0
> certifi==2020.6.20
> chardet==3.0.4
> idna==2.10
> multidict==5.0.0
> python-dateutil==2.8.1
> python-launch-library==1.0.6
> requests==2.24.0
> six==1.15.0
> typing-extensions==3.7.4.3
> Unidecode==1.1.1
> urllib3==1.25.11
> yarl==1.6.2
> 
> I initially had issues where it wouldn't build the wheel when I installed it, but that seemed fixed when I did `pip install wheel`. I'm not sure how to properly install this module, as I'm still getting a ModuleNotFoundError when I try `import launchlibrary` in both the Python console and in a script.
> 
> UPDATE: I don't know what I did wrong, but it's working!

Good to hear that it's working :)
