### ISSUE TITLE
Move to LL2

### ISSUE THREAD

**Issue by Plutoberth** [Plutoberth/python-launch-library#8]
Launchlibrary has announced that the old api will be disabled in the next few months. This wrapper needs to change in order to support LL2 - https://ll.thespacedevs.com/2.0.0/swagger

**Comment by willschlitzer** [comment]
Plutoberth, are you currently working on this? I'm new to open source, but I'm happy to try and work this issue.

**Comment by Plutoberth** [comment]
> 
> 
> Plutoberth, are you currently working on this? I'm new to open source, but I'm happy to try and work this issue.

Hi Will, 

It'd be great if you could take this on. From a ten minute inspection, the new version looks pretty similar except the names of some fields, API endpoints, and stuff like the mode being "detailed" instead of "verbose", but there are probably more differences. I think that there's a dev API endpoint with frozen data and without rate limits, so that could be helpful. Thanks!

**Comment by willschlitzer** [comment]
Thanks! I'll take a look at it. I'm not brand new to Python but still getting used to the web side of things, so my apologies if my work doesn't pan out!

**Comment by Nosudrum** [comment]
Just came across this issue and wanted to remind you that LL1 will be closing down on December 31, 2020.
Starting November 1 there will be a launch asking to move to its successor : Launch Library 2.

You can find more details about the new API on The Space Devs website
https://thespacedevs.com/

And feel free to join our discord server if you need any help moving to LL2 or have any questions
https://discord.gg/p7ntkNA

Cheers !

**Comment by Plutoberth** [comment]
> 
> 
> Just came across this issue and wanted to remind you that LL1 will be closing down on December 31, 2020.
> Starting November 1 there will be a launch asking to move to its successor : Launch Library 2.
> 
> You can find more details about the new API on The Space Devs website
> https://thespacedevs.com/
> 
> And feel free to join our discord server if you need any help moving to LL2 or have any questions
> https://discord.gg/p7ntkNA
> 
> Cheers !

Hi, I appreciate the notification and I'm aware of the change. I'm very busy atm, so I will only be able to update this library a week or so into November.

**Comment by Plutoberth** [comment]
@willschlitzer I'm sorry if you've dedicated some time to this already, I will be taking this issue on.

**Comment by Plutoberth** [comment]
@willschlitzer For your knowledge - OpenAPI defs are provided for the new API. Those can be compiled to create a much better version of this wrapper that supports all endpoints and params. I will probably release a new package which is simply compiled OpenAPI defs soon.

**Comment by willschlitzer** [comment]
@Plutoberth I'm new to this process; why would would create a new package over just updating the current package?

**Comment by Plutoberth** [comment]
> 
> 
> @Plutoberth I'm new to this process; why would would create a new package over just updating the current package?

The new library would be completely different from the current library, because it would be based on auto-generated code from API defs. I updated this library to LL2 so that anyone relying on it (including myself) would only have to make minimal changes.
